### ISSUE TITLE
After installing hdfs3 with conda I got error "Can not find the shared library: libhdfs3.so"

### ISSUE THREAD

**Issue by hsaputra** [conda-forge/hdfs3-feedstock#4]
Doing latest conda install for hdfs3 causing error when trying to import hdfs3 in Python:

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/opt/conda/lib/python3.5/site-packages/hdfs3/lib.py in <module>()
     13 try:
---> 14     _lib = ct.cdll.LoadLibrary('libhdfs3.so')
     15 except OSError:

/opt/conda/lib/python3.5/ctypes/__init__.py in LoadLibrary(self, name)
    424     def LoadLibrary(self, name):
--> 425         return self._dlltype(name)
    426 

/opt/conda/lib/python3.5/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    346         if handle is None:
--> 347             self._handle = _dlopen(self._name, mode)
    348         else:

OSError: /opt/conda/lib/python3.5/lib-dynload/../../libhdfs3.so: undefined symbol: _ZN6google8protobuf2io17CodedOutputStream20WriteVarint64ToArrayEyPh

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-834035ccf0df> in <module>()
----> 1 import hdfs3

/opt/conda/lib/python3.5/site-packages/hdfs3/__init__.py in <module>()
----> 1 from .core import HDFileSystem, HDFile
      2 from .mapping import HDFSMap
      3 
      4 __version__ = '0.1.2'

/opt/conda/lib/python3.5/site-packages/hdfs3/core.py in <module>()
     10 import warnings
     11 from collections import deque
---> 12 from .lib import _lib
     13 
     14 PY3 = sys.version_info.major > 2

/opt/conda/lib/python3.5/site-packages/hdfs3/lib.py in <module>()
     14     _lib = ct.cdll.LoadLibrary('libhdfs3.so')
     15 except OSError:
---> 16     raise ImportError("Can not find the shared library: libhdfs3.so\n"
     17             "See installation instructions at "
     18             "http://hdfs3.readthedocs.io/en/latest/install.html")

ImportError: Can not find the shared library: libhdfs3.so
See installation instructions at http://hdfs3.readthedocs.io/en/latest/install.html
```

I am running it against Ubuntu 14.04.

Seemed like the  libhdfs3.so is not installed, but the conda install hdfs3 pass perfectly.

**Comment by mrocklin** [comment]
Assuming you're not familiar with locating libraries (please forgive me if I'm saying things you already know): 
1. Have you tried `$ locate libhdfs3.so`?  
2. Do you have any magic on your load library path?  
3. Anything that would get in the way of `ct.cdll.LoadLibrary`?
4. What does `$ conda list | grep libhdfs3` return?
5. Is the location of your conda packages on your library path?

The hdfs3 package does depend on libhdfs3, so it should be installed into wherever your `conda` binary lives.  My guess is that your environment is set up in such a way that libraries in that location are not on the system path.

**Comment by hsaputra** [comment]
Looks like libhdfs3 is put under /opt/conda/lib, should I add something like `ENV LD_LIBRARY_PATH /opt/conda/lib:$LD_LIBRARY_PATH` to make sure the so is found?

**Comment by mrocklin** [comment]
Something like that would probably work.  I'm actually not sure what best practices are here.  Mucking with `LD_LIBRARY_PATH` is generally warned against, but I'm not aware of better solutions in this case.

Your question has made me curious now why my own conda installation picks things up automatically without my having to do anything.  I wonder if there is a rule to auto-populate `LD_LIBRARY_PATH` from `PATH`?  Might be worth asking a conda question on stackoverflow to see if they launch Python in a certain way?

**Comment by frol** [comment]
The issue is related to the newer `libprotobuf` package. Downgrading `libprotobuf` to `<3.0` (i.e. `2.5.0-0`) solved the issue.

**Comment by hsaputra** [comment]
Is the libprotobuf transitive dependency from `libhdfs3` install

**Comment by mrocklin** [comment]
This may be resolved by https://github.com/dask/hdfs3/pull/94

On Ubuntu 16.04 I also needed https://github.com/conda-forge/libhdfs3-feedstock/issues/4

**Comment by frol** [comment]
I think the package just needed to be recompiled with a newer libprotobuf.

**Comment by robkoper** [comment]
I have a similar problem with osx. I compiled libhdfs3 for osx, this delivers: libhdfs3.dylib instead of libhdfs3.so.
'from distributed import hdfs' gives the error that it cannot find the libhdfs3.so library. Is there a way to change the path / name to solve this (I am not experienced with this in osx).

**Comment by mrocklin** [comment]
This library does not promise support for osx

**Comment by robkoper** [comment]
Ok, but at the end I managd to compile it happily😀

Groeten,
Rob

> Op 1 okt. 2016 om 19:27 heeft Matthew Rocklin notifications@github.com het volgende geschreven:
> 
> This library does not promise support for osx
>

**Comment by mrocklin** [comment]
Awesome

**Comment by pitrou** [comment]
I have this same problem on Ubuntu 16.04 (same error). I don't know how to downgrade `protobuf`, though:

```
$ conda install -c conda-forge protobuf=2.5
Fetching package metadata .............
Solving package specifications: .


PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels: 
  - protobuf 2.5*

You can search for packages on anaconda.org with

    anaconda search -t conda protobuf

```

**Comment by SharpLu** [comment]
Hello,  I have some issues on Ubuntu 16.4 , the notebook mention.
ImportError: Can not find the shared library:libhdfs3.so
Also tried , Still not working.
conda install hdfs3 -c conda-forge
echo "deb https://dl.bintray.com/wangzw/deb trusty contrib" | sudo tee /etc/apt/sources.list.d/bintray-wangzw-deb.list
sudo apt-get install -y apt-transport-https
sudo apt-get update
sudo apt-get install libhdfs3 libhdfs3-dev
pip install hdfs3

**Comment by koverholt** [comment]
Thanks for the reports. This should be solved in the latest `libhdfs3` conda package that was built from https://github.com/conda-forge/libhdfs3-feedstock/pull/6 with the latest available versions of `protobuf` and `boost`.

I tested `conda install hdfs3 -c conda-forge` on Ubuntu 14.04/16.04 and CentOS 6/7 and things are working for me.

Please reopen or comment if you continue to have issues.

**Comment by v15wk** [comment]
I'm trying to figure out how to resolve the following on OSX:
`"ImportError: Can not find the shared library: libhdfs3.so"`
@robkoper Could you share how you got past the above?

**Comment by SharpLu** [comment]
conda install libhdfs3
pip install libhdfs3
conda install -c clinicalgraphics libgcrypt11
conda install libprotobuf=2.5

if still not working , try to update libhdfs3

**Comment by prcastro** [comment]
I still have to downgrade the protobuf package when installing this one. Maybe this issue should be reopened.

**Comment by martindurant** [comment]
Seems to work OK - are you using the conda-forge channel?
```
root@3921ca7590a0:/# conda create -n tester python=3.6
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /work/miniconda/envs/tester:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2l-0
    pip:        9.0.1-py36_1
    python:     3.6.1-2
    readline:   6.2-2
    setuptools: 27.2.0-py36_0
    sqlite:     3.13.0-0
    tk:         8.5.18-0
    wheel:      0.29.0-py36_0
    xz:         5.2.2-1
    zlib:       1.2.8-3

openssl-1.0.2l 100% |####[..]
# To activate this environment, use:
# > source activate tester
#
# To deactivate this environment, use:
# > source deactivate tester
#

root@3921ca7590a0:/# source activate tester

root@3921ca7590a0:/# conda install hdfs3 -c conda-forge
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /work/miniconda/envs/tester:

The following NEW packages will be INSTALLED:

    boost:     1.63.0-py36_5 conda-forge
    boost-cpp: 1.63.0-2      conda-forge
    bzip2:     1.0.6-1       conda-forge
    hdfs3:     0.1.4-py36_1  conda-forge
    icu:       58.1-1        conda-forge
    krb5:      1.14.2-0      conda-forge
    libgsasl:  1.8.0-0       conda-forge
    libhdfs3:  2.2.31-5      conda-forge
    libiconv:  1.14-4        conda-forge
    libntlm:   1.4-0         conda-forge
    libuuid:   1.0.3-1       conda-forge
    libxml2:   2.9.4-4       conda-forge
    protobuf:  3.3.0-py36_1  conda-forge
    six:       1.10.0-py36_1 conda-forge

bzip2-1.0.6-1. 100% |#######[...]

root@3921ca7590a0:/# python
Python 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:09:58)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hdfs3
>>>
```

**Comment by kpweiler** [comment]
I actually can't get this to work from a clean install of the latest anaconda.

```
$ wget https://repo.continuum.io/archive/Anaconda3-4.4.0-Linux-x86_64.sh
...
$ bash Anaconda3-4.4.0-Linux-x86_64.sh -b
...
$ conda install hdfs3 -c conda-forge
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /export/home/kweiler/anaconda3:

The following NEW packages will be INSTALLED:

    boost:     1.61.0-py36_0
    hdfs3:     0.1.4-py36_1  conda-forge
    krb5:      1.14.2-0      conda-forge
    libgsasl:  1.8.0-0       conda-forge
    libhdfs3:  2.2.31-1      conda-forge
    libntlm:   1.4-0         conda-forge
    libuuid:   1.0.3-1       conda-forge
    protobuf:  3.3.2-py36_0  conda-forge

The following packages will be UPDATED:

    conda:     4.3.21-py36_0             --> 4.3.22-py36_0 conda-forge

The following packages will be SUPERSEDED by a higher-priority channel:

    conda-env: 2.6.0-0                   --> 2.6.0-0       conda-forge

Proceed ([y]/n)? y

conda-env-2.6.
...
$ echo $LD_LIBRARY_PATH

$ python
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:09:58)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hdfs3
Traceback (most recent call last):
  File "/export/home/kweiler/anaconda3/lib/python3.6/site-packages/hdfs3/lib.py", line 14, in <module>
    _lib = ct.cdll.LoadLibrary('libhdfs3.so')
  File "/export/home/kweiler/anaconda3/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/export/home/kweiler/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libprotobuf.so.10: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/export/home/kweiler/anaconda3/lib/python3.6/site-packages/hdfs3/lib.py", line 19, in <module>
    _lib = ct.cdll.LoadLibrary(os.path.join(env, 'lib', 'libhdfs3.so'))
  File "/export/home/kweiler/anaconda3/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/export/home/kweiler/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libprotobuf.so.10: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/home/kweiler/anaconda3/lib/python3.6/site-packages/hdfs3/__init__.py", line 1, in <module>
    from .core import HDFileSystem, HDFile
  File "/export/home/kweiler/anaconda3/lib/python3.6/site-packages/hdfs3/core.py", line 12, in <module>
    from .lib import _lib
  File "/export/home/kweiler/anaconda3/lib/python3.6/site-packages/hdfs3/lib.py", line 21, in <module>
    raise ImportError("Can not find the shared library: libhdfs3.so\n"
ImportError: Can not find the shared library: libhdfs3.so
See installation instructions at http://hdfs3.readthedocs.io/en/latest/install.html
```

What's interesting is that if I do the same steps as you did above inside this newly created environment (create a tester env, etc.). It actually does work:

```
$ conda create -n tester python=3.6
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /export/home/kweiler/anaconda3/envs/tester:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2l-0
    pip:        9.0.1-py36_1
    python:     3.6.2-0
    readline:   6.2-2
    setuptools: 27.2.0-py36_0
    sqlite:     3.13.0-0
    tk:         8.5.18-0
    wheel:      0.29.0-py36_0
    xz:         5.2.2-1
    zlib:       1.2.8-3
...
$ source activate tester
(tester) $ conda install hdfs3 -c conda-forge
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /export/home/kweiler/anaconda3/envs/tester:

The following NEW packages will be INSTALLED:

    boost:     1.63.0-py36_5 conda-forge
    boost-cpp: 1.63.0-2      conda-forge
    bzip2:     1.0.6-1       conda-forge
    hdfs3:     0.1.4-py36_1  conda-forge
    icu:       58.1-1        conda-forge
    krb5:      1.14.2-0      conda-forge
    libgsasl:  1.8.0-0       conda-forge
    libhdfs3:  2.2.31-5      conda-forge
    libiconv:  1.14-4        conda-forge
    libntlm:   1.4-0         conda-forge
    libuuid:   1.0.3-1       conda-forge
    libxml2:   2.9.4-4       conda-forge
    protobuf:  3.3.2-py36_0  conda-forge
    six:       1.10.0-py36_1 conda-forge

Proceed ([y]/n)? y

bzip2-1.0.6-1.
...
(tester) [kweiler@mealybug ~]$ python
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hdfs3
```
The only differences I can see is in the versions of packages (boost, boost-cpp, and libhdfs).

**Comment by kpweiler** [comment]
Incidentally, it also works if I do a clean install of miniconda instead of anaconda.

**Comment by martindurant** [comment]
^ yes, I was surprised by your report, since I was working from miniconda too.

**Comment by jjhelmus** [comment]
I believe the issue with mixing the packages which make up the `anaconda` meta-package (which is included with the Anaconda installed) and the `hdfs3` conda-forge package can be solved by install boost and boost-cpp from conda-forge using `conda install -c conda-forge boost boost-cpp`.  This will update a number of packages, include switching to a different build of `libhdfs3` which I think is the root cause of the issue.

**Comment by quartox** [comment]
I am having similar trouble with the most recent version. 

```
ImportError: Can not find the shared library: libhdfs3.so
See installation instructions at http://hdfs3.readthedocs.io/en/latest/install.html
```

I built my conda environment entirely from conda-forge from the first install. My versions are:
```
hdfs3                     0.2.0                    py36_1    conda-forge
libhdfs3                  2.3                           0    conda-forge
```

In addition, the `libhdfs3.so` is in my environment `lib` folder, so I don't understand why it isn't being found.

**Comment by mrocklin** [comment]
@martindurant it might make sense to add the conda `/lib` path to the `LD_LIBRARY_PATH` environment variable of any YARN containers that we build.

**Comment by martindurant** [comment]
@quartox , is this in YARN or otherwise?

**Comment by quartox** [comment]
@martindurant in YARN. The error points to a trace back on the edge node, but I am trying to read a parquet file on HDFS. Could it be a problem with the container environment?

**Comment by martindurant** [comment]
@quartox , since you have the environment available locally, you could test there. The error shows up whenever libhdfs3 failed to import, which doesn't necessarily mean it isn't there. It may be that you have also mixed anaconda-channel and conda-forge-channel binaries, like some of the people above.

To test:

    >>> import ctyles as ct
    >>> ct.cdll.LoadLibrary('libhdfs3.so')

This will tell you the real error: not found versus some symbol lookup error. The latter would indicate package mismatch. hdfs3 could be changed to always give the underlying error in this situation.

**Comment by quartox** [comment]
@matindurant This yields a seemingly unrelated error 
```
>>> ctypes.cdll.LoadLibrary('libhdfs3.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jlord/.conda/envs/dask/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/home/jlord/.conda/envs/dask/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/jlord/.conda/envs/dask/lib/python3.6/lib-dynload/../.././libcurl.so.4: undefined symbol: libssh2_scp_recv2
```
Nearly all of my binaries are from conda forge, looks like `numba`, `mkl`, `llvmlite`, and `libgfortran` are the only ones not from conda-forge. Should I try building an environment that doesn't allow installs from any channel besides conda-forge (I used `conda create -c conda-forge` but didn't exclude the default channel).

**Comment by martindurant** [comment]
Maybe that implies openssl? 
You shouldn't need to exclude defaults, but do have conda-forge as higher priority (listed first) in either the conda command line options or in .condarc . 
I'm not certain what a good fix for this is: in the short-term I'll probably make libhdfs3 and hdfs3 depend on builds that only exist in conda-forge. In the medium term, the build infrastructure in defaults is being changed to more closely match that in conda-forge, so that should mean the problem naturally goes away.

By the way, since your HDFS is secured, you will need to create a delegate token and pass it to the HDFileSystem constructor (`token=`), since I don't think the yarn container is automatically kinit-ed. Good luck! A yarn delegate token is also available and used by the container on start-up to fetch the environment, but I don't know how you can get hold of that from within.

**Comment by quartox** [comment]
@martindurant It is working after downgrading curl (from conda-forge most recent `7.54.1` to `7.49.1`).

**Comment by martindurant** [comment]
OK, I guess that new builds will be needed against the latest curl.
